# Generated by Django 4.0 on 2022-01-02 12:45

import core.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('second_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=13)),
                ('birthday', models.DateField(default=datetime.date.today, validators=[core.validators.AdultValidator(29)])),
                ('specialization', models.CharField(max_length=70)),
                ('salary', models.PositiveIntegerField(default=1500)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.groups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
