# Generated by Django 4.0 on 2022-01-10 15:36

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=datetime.date.today, validators=[core.validators.AdultValidator(18)]),
        ),
    ]
