    # Generated by Django 4.0 on 2021-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(max_length=1)),
                ('letter', models.CharField(max_length=1)),
                ('fullname', models.CharField(max_length=2)),
                ('number_of_students', models.IntegerField()),
                ('name_of_teacher', models.CharField(max_length=50)),
            ],
        ),
    ]
