# Generated by Django 4.0 on 2022-01-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='end_date',
        ),
    ]
