# Generated by Django 4.0 on 2022-01-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('groups', '0005_alter_groups_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.students'),
        ),
    ]
